### ISSUE TITLE
Fimfiction Advanced not working

### ISSUE THREAD

**Issue by tyrannosaurianrex9-blip** [Sollace/FimFiction-Advanced#1]
I tried clicking on 'Advanced Settings', but it keeps showing normal settings, 
[https://www.fimfiction.net/manage/local-settings#fimfiction_advanced](url)
and I tried clicking on the banner edit, but it keeps showing the home screen.
[https://www.fimfiction.net/?view=page&page=banner_credits](url)

Can you explain and fix this for me? If you didn't see what I see, maybe my computer is badly connected.

**Comment by Sollace** [comment]
Should be fixed in the 1.7.2 update
