### ISSUE TITLE
FimFiction Advanced keeps logout on its own

### ISSUE THREAD

**Issue by tyrannosaurianrex9-blip** [Sollace/FimFiction-Advanced#2]
Every time I log into FimFiction, the home screen only shows standard FimFiction, and I try to refresh it, but it wouldn't let me switch to 'Advanced' for the most part. Don't believe me? Check this out:
![Screenshot (4)](https://user-images.githubusercontent.com/67716703/200351778-05701575-e3a0-4974-8db4-22affa5306ab.png)

**Comment by Sollace** [comment]
Fixed in 1.7.2. Reinstall the script if you still have issues
